# Generated by Django 6.0.3 on 2026-03-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('textColor', models.CharField(max_length=20)),
                ('actionIconColor', models.CharField(max_length=20)),
                ('actionBg', models.URLField(blank=True, null=True)),
                ('keyboardBg', models.URLField(blank=True, null=True)),
                ('keyboardBgColor', models.CharField(max_length=20)),
                ('keysBg', models.URLField(blank=True, null=True)),
                ('isPremium', models.BooleanField(default=False)),
                ('downloads', models.IntegerField(default=0)),
                ('sortOrder', models.IntegerField(default=0)),
                ('createdAt', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='api.category')),
            ],
        ),
    ]
